=begin
#configapi

#Config API lets you easily manage configuration at scale.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'date'

module CloudmersiveConfigurationApiClient
  # Value of a setting
  class SettingValue
    # The ID of the setting value
    attr_accessor :config_setting_value_id

    # The ID of the definition of the setting
    attr_accessor :config_setting_definition_id

    # The value of the setting
    attr_accessor :config_setting_value

    # The last modified date of the setting
    attr_accessor :config_setting_last_modified

    # Name of the setting
    attr_accessor :config_setting_name

    # Description of the setting
    attr_accessor :config_setting_description

    # Setting tags
    attr_accessor :config_setting_tags

    # Possible values are: STRING, JSON
    attr_accessor :config_setting_type

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'config_setting_value_id' => :'ConfigSettingValueID',
        :'config_setting_definition_id' => :'ConfigSettingDefinitionID',
        :'config_setting_value' => :'ConfigSettingValue',
        :'config_setting_last_modified' => :'ConfigSettingLastModified',
        :'config_setting_name' => :'ConfigSettingName',
        :'config_setting_description' => :'ConfigSettingDescription',
        :'config_setting_tags' => :'ConfigSettingTags',
        :'config_setting_type' => :'ConfigSettingType'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'config_setting_value_id' => :'String',
        :'config_setting_definition_id' => :'String',
        :'config_setting_value' => :'Object',
        :'config_setting_last_modified' => :'DateTime',
        :'config_setting_name' => :'String',
        :'config_setting_description' => :'String',
        :'config_setting_tags' => :'String',
        :'config_setting_type' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'ConfigSettingValueID')
        self.config_setting_value_id = attributes[:'ConfigSettingValueID']
      end

      if attributes.has_key?(:'ConfigSettingDefinitionID')
        self.config_setting_definition_id = attributes[:'ConfigSettingDefinitionID']
      end

      if attributes.has_key?(:'ConfigSettingValue')
        self.config_setting_value = attributes[:'ConfigSettingValue']
      end

      if attributes.has_key?(:'ConfigSettingLastModified')
        self.config_setting_last_modified = attributes[:'ConfigSettingLastModified']
      end

      if attributes.has_key?(:'ConfigSettingName')
        self.config_setting_name = attributes[:'ConfigSettingName']
      end

      if attributes.has_key?(:'ConfigSettingDescription')
        self.config_setting_description = attributes[:'ConfigSettingDescription']
      end

      if attributes.has_key?(:'ConfigSettingTags')
        self.config_setting_tags = attributes[:'ConfigSettingTags']
      end

      if attributes.has_key?(:'ConfigSettingType')
        self.config_setting_type = attributes[:'ConfigSettingType']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          config_setting_value_id == o.config_setting_value_id &&
          config_setting_definition_id == o.config_setting_definition_id &&
          config_setting_value == o.config_setting_value &&
          config_setting_last_modified == o.config_setting_last_modified &&
          config_setting_name == o.config_setting_name &&
          config_setting_description == o.config_setting_description &&
          config_setting_tags == o.config_setting_tags &&
          config_setting_type == o.config_setting_type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [config_setting_value_id, config_setting_definition_id, config_setting_value, config_setting_last_modified, config_setting_name, config_setting_description, config_setting_tags, config_setting_type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CloudmersiveConfigurationApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
