=begin
#configapi

#Config API lets you easily manage configuration at scale.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveConfigurationApiClient::SettingsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SettingsApi' do
  before do
    # run before each test
    @instance = CloudmersiveConfigurationApiClient::SettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsApi' do
    it 'should create an instance of SettingsApi' do
      expect(@instance).to be_instance_of(CloudmersiveConfigurationApiClient::SettingsApi)
    end
  end

  # unit tests for settings_create_setting
  # Create a setting in the specified bucket
  # @param request Request to perform the operation on
  # @param [Hash] opts the optional parameters
  # @return [CreateSettingResponse]
  describe 'settings_create_setting test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for settings_list_settings
  # Enumerate the settings in a bucket
  # @param request Request to perform the operation on
  # @param [Hash] opts the optional parameters
  # @return [ListSettingsResponse]
  describe 'settings_list_settings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for settings_update_setting
  # Update a setting
  # @param request Request to perform the operation on
  # @param [Hash] opts the optional parameters
  # @return [UpdateSettingResponse]
  describe 'settings_update_setting test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
