=begin
#configapi

#Config API lets you easily manage configuration at scale.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'cloudmersive-configuration-api-client/api_client'
require 'cloudmersive-configuration-api-client/api_error'
require 'cloudmersive-configuration-api-client/version'
require 'cloudmersive-configuration-api-client/configuration'

# Models
require 'cloudmersive-configuration-api-client/models/create_setting_request'
require 'cloudmersive-configuration-api-client/models/create_setting_response'
require 'cloudmersive-configuration-api-client/models/http_form_data_parameter'
require 'cloudmersive-configuration-api-client/models/http_get_parameter'
require 'cloudmersive-configuration-api-client/models/http_orchestration_header'
require 'cloudmersive-configuration-api-client/models/http_orchestration_request'
require 'cloudmersive-configuration-api-client/models/http_orchestration_response'
require 'cloudmersive-configuration-api-client/models/http_orchestration_task'
require 'cloudmersive-configuration-api-client/models/http_raw_binary_parameter'
require 'cloudmersive-configuration-api-client/models/http_raw_text_parameter'
require 'cloudmersive-configuration-api-client/models/http_www_form_url_encoded_parameter'
require 'cloudmersive-configuration-api-client/models/list_settings_request'
require 'cloudmersive-configuration-api-client/models/list_settings_response'
require 'cloudmersive-configuration-api-client/models/setting_value'
require 'cloudmersive-configuration-api-client/models/task_output_reference'
require 'cloudmersive-configuration-api-client/models/update_setting_request'
require 'cloudmersive-configuration-api-client/models/update_setting_response'

# APIs
require 'cloudmersive-configuration-api-client/api/orchestrator_api'
require 'cloudmersive-configuration-api-client/api/settings_api'

module CloudmersiveConfigurationApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveConfigurationApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
